image: node:latest

stages:
  - build
  - deploy

before_script:
  - npm config set spin false
  - npm install -g ember-cli
  - npm install

build:
  stage: build
  script:
    - ember build --prod

pages:
  stage: deploy
  script:
    - ember build --prod
  artifacts:
    paths:
      - public
  only:
    - master
